#!/usr/bin/env python3
env = '''APP_NAME="NXLY Exam Arena"
APP_ENV=production
APP_DEBUG=false
APP_URL=https://exam-arena.lc-synergy.ltd

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_LEVEL=error

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=lcsyxfen_exam-arena
DB_USERNAME=lcsyxfen_exam-arena
DB_PASSWORD="kReEMq=c}h,W.Tgb"

SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_CONNECTION=database
CACHE_STORE=file

BROADCAST_CONNECTION=pusher
FILESYSTEM_DISK=local

PUSHER_APP_ID=1937309
PUSHER_APP_KEY=f7507d80e31f711dfcff
PUSHER_APP_SECRET=211927994bef17478751
PUSHER_APP_CLUSTER=mt1
PUSHER_PORT=443
PUSHER_SCHEME=https

VITE_PUSHER_APP_KEY=f7507d80e31f711dfcff
VITE_PUSHER_APP_CLUSTER=mt1

MAIL_MAILER=smtp
MAIL_SCHEME=smtps
MAIL_HOST=exam-arena.lc-synergy.ltd
MAIL_PORT=465
MAIL_USERNAME=exam-arena@exam-arena.lc-synergy.ltd
MAIL_PASSWORD="r&K.Qre[eY9x+]iu"
MAIL_FROM_ADDRESS=exam-arena@exam-arena.lc-synergy.ltd
MAIL_FROM_NAME="NXLY Exam Arena"

FIREBASE_CREDENTIALS=storage/app/firebase-service-account.json
FIREBASE_PROJECT_ID=exam-arena-6148c
FIREBASE_VAPID_PUBLIC_KEY=BKPEwvQSYwZhDuz0M3Bxodhf4Um980h5IvJJrIWcERJopbvV6JabGrSyk69lre_cOpqfRIAPsrhpMwVNvAjmWfc

VITE_FIREBASE_API_KEY=AIzaSyDp_Af0POFa-EekqDEFdgLzVLNSAtYbU10
VITE_FIREBASE_AUTH_DOMAIN=exam-arena-6148c.firebaseapp.com
VITE_FIREBASE_PROJECT_ID=exam-arena-6148c
VITE_FIREBASE_STORAGE_BUCKET=exam-arena-6148c.firebasestorage.app
VITE_FIREBASE_MESSAGING_SENDER_ID=165082016850
VITE_FIREBASE_APP_ID=1:165082016850:web:9fb8f973b6e20743b4038b
VITE_FIREBASE_MEASUREMENT_ID=G-01YZ8W7R3X
VITE_FIREBASE_VAPID_KEY=BKPEwvQSYwZhDuz0M3Bxodhf4Um980h5IvJJrIWcERJopbvV6JabGrSyk69lre_cOpqfRIAPsrhpMwVNvAjmWfc

GEMINI_API_KEY_1=AQ.Ab8RN6LJk5dB3HlEEPcXYt_Et-YeBUFIiB4HvyX9Va8OPGNJHw
GEMINI_CHAT_MODEL=gemini-2.0-flash
GEMINI_QUESTION_MODEL=gemini-2.5-pro

GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=https://exam-arena.lc-synergy.ltd/auth/google/callback

SMS_DRIVER=log
'''

with open('/home/lcsyxfen/exam-arena-app/.env', 'w') as f:
    f.write(env.lstrip())

print('Production .env written cleanly!')
